SELECT 
    i.REST_ID, 
    REST_NAME, 
    FOOD_TYPE, 
    FAVORITES, 
    ADDRESS,
    FORMAT(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW r
JOIN REST_INFO i ON r.REST_ID = i.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC;

